version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  labels: []
- package-ecosystem: pip
  directory: /
  schedule:
    interval: monthly
  allow:
  - dependency-type: direct
  labels: []
  ignore:
  # Old version required for Python 3.5
  - dependency-name: freezegun
  - dependency-name: colorama
