language: python

dist: xenial
sudo: required

python:
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install -e .[dev]

script:
  - pytest --cov loguru/

after_success:
  - codecov
  - cd docs && make html
