language: python

dist: xenial

sudo: required

python:
  - '3.5.2'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy3.5'

install:
  - pip install tox-travis codecov

script: tox

after_success:
  - codecov --flags "python_${TRAVIS_PYTHON_VERSION//[^[:alnum:]]/}"
