language: python

dist: xenial

sudo: required

python:
  - '3.5'
  - '3.6'
  - '3.7'
  - 'pypy3.5'

install:
  - pip install tox-travis codecov

script:
  - tox
  - codecov --required --flags "py_${TRAVIS_PYTHON_VERSION//[^[:alnum:]]/}"
